import {Media} from '../Global/Media';

export const job_data = [
  {
    id: 1,
    name: 'Sandhiya',
    job_role: 'Graphic Designer',
    location: 'Coimbatore',
    experience: '3Y 11M',
    expectedCTC: '4 LPA',
    image: Media.user,
    is_saved: true,
    skills: [
      {
        id: 1,
        name: 'Adobe',
      },
      {
        id: 2,
        name: 'Illustrate',
      },
      {
        id: 3,
        name: 'Adobe XD',
      },
      {
        id: 4,
        name: 'Figma',
      },
    ],
    candidate_experiences: [
      {
        id: 1,
        company: 'Tech Solutions Inc...',
        department: 'Software Development',
        designation: 'Senior Software Engineer',
        start: '2016-07-01',
        end: null,
        responsibilities: 'Lead a team of developers in project delivery.',
        created_at: '2016-07-01T08:00:00Z',
        updated_at: '2024-04-06T10:30:00Z',
        currently_working: true,
      },
      {
        id: 2,
        company: 'Tech Solutions Inc...',
        department: 'Software Development',
        designation: 'Senior Software Engineer',
        start: '2016-07-01',
        end: null,
        responsibilities: 'Lead a team of developers in project delivery.',
        created_at: '2016-07-01T08:00:00Z',
        updated_at: '2024-04-06T10:30:00Z',
        currently_working: true,
      },
    ],
    candidate_education: [
      {
        id: 1,
        institute_name: 'RVS College Of Arts and scinence',
        degree: 'Bachelor of Science in Computer Science',
        year: '2012-2016',
        notes: 'Graduated with honors',
        created_at: '2016-05-30T08:00:00Z',
        updated_at: '2016-05-30T08:00:00Z',
      },
      {
        id: 2,
        institute_name: 'Government Hr sec school - iduvampalayam',
        degree: 'HSC',
        year: '2012-2016',
        notes: 'Graduated with honors',
        created_at: '2016-05-30T08:00:00Z',
        updated_at: '2016-05-30T08:00:00Z',
      },
    ],
    phone: '1234567890',
    email: 'gokul@avanexa.com',
    website: 'gokulraj.com',
    address:
      '24, Vinayagar Koil St, Krishnaswamy Nagar, Sowripalayam Pirivu, Ramanathapuram, Coimbatore, Tamil Nadu 641045',
    gender: 'Male',
    birth_date: '2024-05-16T12:06:03.566Z',
    marital_status: 'single',
    candidate_language: [
      {
        id: 1,
        name: 'Tamil',
      },
      {
        id: 2,
        name: 'English',
      },
    ],
    candidate_resume: [
      {
        id: 1,
        name: 'Dummy.pdf',
        file: 'https://www.clickdimensions.com/links/TestPDFfile.pdf',
      },
    ],
    cover_letter: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries`,
    created_at: '2024-05-16T12:06:03.566Z',
  },
  {
    id: 2,
    name: 'Sandhiya',
    job_role: 'Graphic Designer',
    location: 'Coimbatore',
    experience: '3Y 11M',
    expectedCTC: '4 LPA',
    image: Media.user,
    is_saved: true,
    skills: [
      {
        id: 1,
        name: 'Adobe',
      },
      {
        id: 2,
        name: 'Illustrate',
      },
      {
        id: 3,
        name: 'Adobe XD',
      },
      {
        id: 4,
        name: 'Figma',
      },
    ],
    candidate_experiences: [
      {
        id: 1,
        company: 'Tech Solutions Inc...',
        department: 'Software Development',
        designation: 'Senior Software Engineer',
        start: '2016-07-01',
        end: null,
        responsibilities: 'Lead a team of developers in project delivery.',
        created_at: '2016-07-01T08:00:00Z',
        updated_at: '2024-04-06T10:30:00Z',
        currently_working: true,
      },
      {
        id: 2,
        company: 'Tech Solutions Inc...',
        department: 'Software Development',
        designation: 'Senior Software Engineer',
        start: '2016-07-01',
        end: null,
        responsibilities: 'Lead a team of developers in project delivery.',
        created_at: '2016-07-01T08:00:00Z',
        updated_at: '2024-04-06T10:30:00Z',
        currently_working: true,
      },
    ],
    candidate_education: [
      {
        id: 1,
        institute_name: 'RVS College Of Arts and scinence',
        degree: 'Bachelor of Science in Computer Science',
        year: '2012-2016',
        notes: 'Graduated with honors',
        created_at: '2016-05-30T08:00:00Z',
        updated_at: '2016-05-30T08:00:00Z',
      },
      {
        id: 2,
        institute_name: 'Government Hr sec school - iduvampalayam',
        degree: 'HSC',
        year: '2012-2016',
        notes: 'Graduated with honors',
        created_at: '2016-05-30T08:00:00Z',
        updated_at: '2016-05-30T08:00:00Z',
      },
    ],
    phone: '1234567890',
    email: 'gokul@avanexa.com',
    website: 'gokulraj.com',
    address:
      '24, Vinayagar Koil St, Krishnaswamy Nagar, Sowripalayam Pirivu, Ramanathapuram, Coimbatore, Tamil Nadu 641045',
    gender: 'Male',
    birth_date: '2024-05-16T12:06:03.566Z',
    marital_status: 'single',
    candidate_language: [
      {
        id: 1,
        name: 'Tamil',
      },
      {
        id: 2,
        name: 'English',
      },
    ],
    candidate_resume: [
      {
        id: 1,
        name: 'Dummy.pdf',
        file: 'https://www.clickdimensions.com/links/TestPDFfile.pdf',
      },
    ],
    cover_letter: 'mobile',
    created_at: '2024-05-16T12:06:03.566Z',
  },
  {
    id: 3,
    name: 'Sandhiya',
    job_role: 'Graphic Designer',
    location: 'Coimbatore',
    experience: '3Y 11M',
    expectedCTC: '4 LPA',
    image: Media.user,
    is_saved: true,
    skills: [
      {
        id: 1,
        name: 'Adobe',
      },
      {
        id: 2,
        name: 'Illustrate',
      },
      {
        id: 3,
        name: 'Adobe XD',
      },
      {
        id: 4,
        name: 'Figma',
      },
    ],
    candidate_experiences: [
      {
        id: 1,
        company: 'Tech Solutions Inc...',
        department: 'Software Development',
        designation: 'Senior Software Engineer',
        start: '2016-07-01',
        end: null,
        responsibilities: 'Lead a team of developers in project delivery.',
        created_at: '2016-07-01T08:00:00Z',
        updated_at: '2024-04-06T10:30:00Z',
        currently_working: true,
      },
      {
        id: 2,
        company: 'Tech Solutions Inc...',
        department: 'Software Development',
        designation: 'Senior Software Engineer',
        start: '2016-07-01',
        end: null,
        responsibilities: 'Lead a team of developers in project delivery.',
        created_at: '2016-07-01T08:00:00Z',
        updated_at: '2024-04-06T10:30:00Z',
        currently_working: true,
      },
    ],
    candidate_education: [
      {
        id: 1,
        institute_name: 'RVS College Of Arts and scinence',
        degree: 'Bachelor of Science in Computer Science',
        year: '2012-2016',
        notes: 'Graduated with honors',
        created_at: '2016-05-30T08:00:00Z',
        updated_at: '2016-05-30T08:00:00Z',
      },
      {
        id: 2,
        institute_name: 'Government Hr sec school - iduvampalayam',
        degree: 'HSC',
        year: '2012-2016',
        notes: 'Graduated with honors',
        created_at: '2016-05-30T08:00:00Z',
        updated_at: '2016-05-30T08:00:00Z',
      },
    ],
    phone: '1234567890',
    email: 'gokul@avanexa.com',
    website: 'gokulraj.com',
    address:
      '24, Vinayagar Koil St, Krishnaswamy Nagar, Sowripalayam Pirivu, Ramanathapuram, Coimbatore, Tamil Nadu 641045',
    gender: 'Male',
    birth_date: '2024-05-16T12:06:03.566Z',
    marital_status: 'single',
    candidate_language: [
      {
        id: 1,
        name: 'Tamil',
      },
      {
        id: 2,
        name: 'English',
      },
    ],
    candidate_resume: [
      {
        id: 1,
        name: 'Dummy.pdf',
        file: 'https://www.clickdimensions.com/links/TestPDFfile.pdf',
      },
    ],
    cover_letter: 'mobile',
    created_at: '2024-05-16T12:06:03.566Z',
  },
  {
    id: 4,
    name: 'Sandhiya',
    job_role: 'Graphic Designer',
    location: 'Coimbatore',
    experience: '3Y 11M',
    expectedCTC: '4 LPA',
    image: Media.user,
    is_saved: true,
    skills: [
      {
        id: 1,
        name: 'Adobe',
      },
      {
        id: 2,
        name: 'Illustrate',
      },
      {
        id: 3,
        name: 'Adobe XD',
      },
      {
        id: 4,
        name: 'Figma',
      },
    ],
    candidate_experiences: [
      {
        id: 1,
        company: 'Tech Solutions Inc...',
        department: 'Software Development',
        designation: 'Senior Software Engineer',
        start: '2016-07-01',
        end: null,
        responsibilities: 'Lead a team of developers in project delivery.',
        created_at: '2016-07-01T08:00:00Z',
        updated_at: '2024-04-06T10:30:00Z',
        currently_working: true,
      },
      {
        id: 2,
        company: 'Tech Solutions Inc...',
        department: 'Software Development',
        designation: 'Senior Software Engineer',
        start: '2016-07-01',
        end: null,
        responsibilities: 'Lead a team of developers in project delivery.',
        created_at: '2016-07-01T08:00:00Z',
        updated_at: '2024-04-06T10:30:00Z',
        currently_working: true,
      },
    ],
    candidate_education: [
      {
        id: 1,
        institute_name: 'RVS College Of Arts and scinence',
        degree: 'Bachelor of Science in Computer Science',
        year: '2012-2016',
        notes: 'Graduated with honors',
        created_at: '2016-05-30T08:00:00Z',
        updated_at: '2016-05-30T08:00:00Z',
      },
      {
        id: 2,
        institute_name: 'Government Hr sec school - iduvampalayam',
        degree: 'HSC',
        year: '2012-2016',
        notes: 'Graduated with honors',
        created_at: '2016-05-30T08:00:00Z',
        updated_at: '2016-05-30T08:00:00Z',
      },
    ],
    phone: '1234567890',
    email: 'gokul@avanexa.com',
    website: 'gokulraj.com',
    address:
      '24, Vinayagar Koil St, Krishnaswamy Nagar, Sowripalayam Pirivu, Ramanathapuram, Coimbatore, Tamil Nadu 641045',
    gender: 'Male',
    birth_date: '2024-05-16T12:06:03.566Z',
    marital_status: 'single',
    candidate_language: [
      {
        id: 1,
        name: 'Tamil',
      },
      {
        id: 2,
        name: 'English',
      },
    ],
    candidate_resume: [
      {
        id: 1,
        name: 'Dummy.pdf',
        file: 'https://www.clickdimensions.com/links/TestPDFfile.pdf',
      },
    ],
    cover_letter: 'mobile',
    created_at: '2024-05-16T12:06:03.566Z',
  },
  {
    id: 5,
    name: 'Sandhiya',
    job_role: 'Graphic Designer',
    location: 'Coimbatore',
    experience: '3Y 11M',
    expectedCTC: '4 LPA',
    image: Media.user,
    is_saved: true,
    skills: [
      {
        id: 1,
        name: 'Adobe',
      },
      {
        id: 2,
        name: 'Illustrate',
      },
      {
        id: 3,
        name: 'Adobe XD',
      },
      {
        id: 4,
        name: 'Figma',
      },
    ],
    candidate_experiences: [
      {
        id: 1,
        company: 'Tech Solutions Inc...',
        department: 'Software Development',
        designation: 'Senior Software Engineer',
        start: '2016-07-01',
        end: null,
        responsibilities: 'Lead a team of developers in project delivery.',
        created_at: '2016-07-01T08:00:00Z',
        updated_at: '2024-04-06T10:30:00Z',
        currently_working: true,
      },
      {
        id: 2,
        company: 'Tech Solutions Inc...',
        department: 'Software Development',
        designation: 'Senior Software Engineer',
        start: '2016-07-01',
        end: null,
        responsibilities: 'Lead a team of developers in project delivery.',
        created_at: '2016-07-01T08:00:00Z',
        updated_at: '2024-04-06T10:30:00Z',
        currently_working: true,
      },
    ],
    candidate_education: [
      {
        id: 1,
        institute_name: 'RVS College Of Arts and scinence',
        degree: 'Bachelor of Science in Computer Science',
        year: '2012-2016',
        notes: 'Graduated with honors',
        created_at: '2016-05-30T08:00:00Z',
        updated_at: '2016-05-30T08:00:00Z',
      },
      {
        id: 2,
        institute_name: 'Government Hr sec school - iduvampalayam',
        degree: 'HSC',
        year: '2012-2016',
        notes: 'Graduated with honors',
        created_at: '2016-05-30T08:00:00Z',
        updated_at: '2016-05-30T08:00:00Z',
      },
    ],
    phone: '1234567890',
    email: 'gokul@avanexa.com',
    website: 'gokulraj.com',
    address:
      '24, Vinayagar Koil St, Krishnaswamy Nagar, Sowripalayam Pirivu, Ramanathapuram, Coimbatore, Tamil Nadu 641045',
    gender: 'Male',
    birth_date: '2024-05-16T12:06:03.566Z',
    marital_status: 'single',
    candidate_language: [
      {
        id: 1,
        name: 'Tamil',
      },
      {
        id: 2,
        name: 'English',
      },
    ],
    candidate_resume: [
      {
        id: 1,
        name: 'Dummy.pdf',
        file: 'https://www.clickdimensions.com/links/TestPDFfile.pdf',
      },
    ],
    cover_letter: 'mobile',
    created_at: '2024-05-16T12:06:03.566Z',
  },
  {
    id: 6,
    name: 'Sandhiya',
    job_role: 'Graphic Designer',
    location: 'Coimbatore',
    experience: '3Y 11M',
    expectedCTC: '4 LPA',
    image: Media.user,
    is_saved: true,
    skills: [
      {
        id: 1,
        name: 'Adobe',
      },
      {
        id: 2,
        name: 'Illustrate',
      },
      {
        id: 3,
        name: 'Adobe XD',
      },
      {
        id: 4,
        name: 'Figma',
      },
    ],
    candidate_experiences: [
      {
        id: 1,
        company: 'Tech Solutions Inc...',
        department: 'Software Development',
        designation: 'Senior Software Engineer',
        start: '2016-07-01',
        end: null,
        responsibilities: 'Lead a team of developers in project delivery.',
        created_at: '2016-07-01T08:00:00Z',
        updated_at: '2024-04-06T10:30:00Z',
        currently_working: true,
      },
      {
        id: 2,
        company: 'Tech Solutions Inc...',
        department: 'Software Development',
        designation: 'Senior Software Engineer',
        start: '2016-07-01',
        end: null,
        responsibilities: 'Lead a team of developers in project delivery.',
        created_at: '2016-07-01T08:00:00Z',
        updated_at: '2024-04-06T10:30:00Z',
        currently_working: true,
      },
    ],
    candidate_education: [
      {
        id: 1,
        institute_name: 'RVS College Of Arts and scinence',
        degree: 'Bachelor of Science in Computer Science',
        year: '2012-2016',
        notes: 'Graduated with honors',
        created_at: '2016-05-30T08:00:00Z',
        updated_at: '2016-05-30T08:00:00Z',
      },
      {
        id: 2,
        institute_name: 'Government Hr sec school - iduvampalayam',
        degree: 'HSC',
        year: '2012-2016',
        notes: 'Graduated with honors',
        created_at: '2016-05-30T08:00:00Z',
        updated_at: '2016-05-30T08:00:00Z',
      },
    ],
    phone: '1234567890',
    email: 'gokul@avanexa.com',
    website: 'gokulraj.com',
    address:
      '24, Vinayagar Koil St, Krishnaswamy Nagar, Sowripalayam Pirivu, Ramanathapuram, Coimbatore, Tamil Nadu 641045',
    gender: 'Male',
    birth_date: '2024-05-16T12:06:03.566Z',
    marital_status: 'single',
    candidate_language: [
      {
        id: 1,
        name: 'Tamil',
      },
      {
        id: 2,
        name: 'English',
      },
    ],
    candidate_resume: [
      {
        id: 1,
        name: 'Dummy.pdf',
        file: 'https://www.clickdimensions.com/links/TestPDFfile.pdf',
      },
    ],
    cover_letter: 'mobile',
    created_at: '2024-05-16T12:06:03.566Z',
  },
  {
    id: 7,
    name: 'Sandhiya',
    job_role: 'Graphic Designer',
    location: 'Coimbatore',
    experience: '3Y 11M',
    expectedCTC: '4 LPA',
    image: Media.user,
    is_saved: true,
    skills: [
      {
        id: 1,
        name: 'Adobe',
      },
      {
        id: 2,
        name: 'Illustrate',
      },
      {
        id: 3,
        name: 'Adobe XD',
      },
      {
        id: 4,
        name: 'Figma',
      },
    ],
    candidate_experiences: [
      {
        id: 1,
        company: 'Tech Solutions Inc...',
        department: 'Software Development',
        designation: 'Senior Software Engineer',
        start: '2016-07-01',
        end: null,
        responsibilities: 'Lead a team of developers in project delivery.',
        created_at: '2016-07-01T08:00:00Z',
        updated_at: '2024-04-06T10:30:00Z',
        currently_working: true,
      },
      {
        id: 2,
        company: 'Tech Solutions Inc...',
        department: 'Software Development',
        designation: 'Senior Software Engineer',
        start: '2016-07-01',
        end: null,
        responsibilities: 'Lead a team of developers in project delivery.',
        created_at: '2016-07-01T08:00:00Z',
        updated_at: '2024-04-06T10:30:00Z',
        currently_working: true,
      },
    ],
    candidate_education: [
      {
        id: 1,
        institute_name: 'RVS College Of Arts and scinence',
        degree: 'Bachelor of Science in Computer Science',
        year: '2012-2016',
        notes: 'Graduated with honors',
        created_at: '2016-05-30T08:00:00Z',
        updated_at: '2016-05-30T08:00:00Z',
      },
      {
        id: 2,
        institute_name: 'Government Hr sec school - iduvampalayam',
        degree: 'HSC',
        year: '2012-2016',
        notes: 'Graduated with honors',
        created_at: '2016-05-30T08:00:00Z',
        updated_at: '2016-05-30T08:00:00Z',
      },
    ],
    phone: '1234567890',
    email: 'gokul@avanexa.com',
    website: 'gokulraj.com',
    address:
      '24, Vinayagar Koil St, Krishnaswamy Nagar, Sowripalayam Pirivu, Ramanathapuram, Coimbatore, Tamil Nadu 641045',
    gender: 'Male',
    birth_date: '2024-05-16T12:06:03.566Z',
    marital_status: 'single',
    candidate_language: [
      {
        id: 1,
        name: 'Tamil',
      },
      {
        id: 2,
        name: 'English',
      },
    ],
    candidate_resume: [
      {
        id: 1,
        name: 'Dummy.pdf',
        file: 'https://www.clickdimensions.com/links/TestPDFfile.pdf',
      },
    ],
    cover_letter: 'mobile',
    created_at: '2024-05-16T12:06:03.566Z',
  },
];

export const job_posting = [
  {
    id: 1,
    name: 'Santhya',
    job_role: 'UI/UX Designer',
    image: Media.user,
    action: 'call',
    job_type: 'Full Time',
    applicants: '2',
    created_at: '2024-05-16T12:06:03.566Z',
    end_date: '2024-05-30T12:06:03.566Z',
  },
  {
    id: 2,
    name: 'Arjun',
    job_role: 'Senior Research Executive',
    image: Media.user,
    action: 'mail',
    job_type: 'Full Time',
    applicants: '2',
    created_at: '2024-05-18T12:06:03.566Z',
    end_date: '2024-05-30T12:06:03.566Z',
  },
  {
    id: 3,
    name: 'Santhya',
    job_role: 'Senior Research Executive',
    image: Media.user,
    action: 'call',
    job_type: 'Full Time',
    applicants: '2',
    created_at: '2024-05-18T12:06:03.566Z',
    end_date: '2024-05-30T12:06:03.566Z',
  },
];

export const categories_data = [
  {
    id: 1,
    name: 'All Jobs',
  },
  {
    id: 2,
    name: 'Mobile Application',
  },
  {
    id: 3,
    name: 'Web Application',
  },
  {
    id: 4,
    name: 'UI/UX Desiners',
  },
  {
    id: 5,
    name: 'SEO',
  },
  {
    id: 6,
    name: 'Junior Devops Engineer',
  },
];
